CREATE TABLE USERS (
  ID            NUMBER(22) PRIMARY KEY,
  FIRST_NAME    VARCHAR2(60),
  LAST_NAME     VARCHAR2(60),
  PASSPORT      NUMBER(22) UNIQUE
);

CREATE TABLE INTERNET_PACKAGES (
  ID                         NUMBER(22) PRIMARY KEY,
  GIGA_BYTES                 DECIMAL,
  USAGE_START                TIMESTAMP(3) DEFAULT SYSDATE,
  EXPIRATION_DATE            TIMESTAMP(3) DEFAULT SYSDATE
);

CREATE TABLE MINUTES_PACKAGES (
  ID                         NUMBER(22) PRIMARY KEY,
  MINUTES                    NUMBER(22),
  USAGE_START                TIMESTAMP(3) DEFAULT SYSDATE,
  EXPIRATION_DATE            TIMESTAMP(3) DEFAULT SYSDATE
);

CREATE TABLE SIM_CARDS (
  ID                         NUMBER(22) PRIMARY KEY,
  USER_ID                    NUMBER(22),
  PHONE_NUMBER               NUMBER(10) UNIQUE,
  ACTIVE                     NUMBER(1),
  REGISTRATION_DATE          TIMESTAMP(3) DEFAULT SYSDATE,
  INTERNET_PACKAGE_ID        NUMBER(22),
  MINUTES_PACKAGE_ID         NUMBER(22),

  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT FK_INTERNET_PACKAGE_ID FOREIGN KEY (INTERNET_PACKAGE_ID) REFERENCES INTERNET_PACKAGES (ID),
  CONSTRAINT FK_MINUTES_PACKAGE_ID FOREIGN KEY (MINUTES_PACKAGE_ID) REFERENCES MINUTES_PACKAGES (ID)
);

CREATE SEQUENCE "USER_SEQ" MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE "SIM_SEQ" MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 10 CACHE 20;
CREATE SEQUENCE "PACKAGE_SEQ" MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 50 CACHE 20;
